## Import functions, libraries and data

In [1]:
import pandas as pd
import numpy as np

# import existing dataset
csv_data = pd.read_csv("data_constructed.csv", parse_dates=['Zeitstempel'])
data = pd.DataFrame(csv_data)

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22266 entries, 0 to 22265
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Artikel                      22266 non-null  object
 1   ArtikelNr                    22266 non-null  int64
 2   Menge                        22266 non-null  float64
 3   Temperatur Schnitt Tag       22266 non-null  float64
 4   Niederschlag Summe Tag       22266 non-null  float64
 5   Globalstrahlung Schnitt Tag  22266 non-null  float64
 6   Zeitstempel                  22266 non-null  datetime64[ns]
 7   day_of_week                  22266 non-null  int64
 8   day_of_year                  22266 non-null  int64
 9   month                        22266 non-null  int64
 10  year                         22266 non-null  int64
 11  Menge_log                    22266 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(5), object(1)
memory usage: 2.0+ MB

## Import more data

### Import Feiertage

In [3]:
feiertage = pd.read_csv('feiertage.csv', parse_dates=['Zeitstempel'], dayfirst=True)
feiertage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Zeitstempel    45 non-null     datetime64[ns]
 1   Feiertag       45 non-null     object
 2   Feiertag_bool  45 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 1.2+ KB

### Import Ferientage

In [4]:
# Import Feriendaten.csv
ferien = pd.read_csv('Feriendaten.csv', parse_dates=['Zeitstempel'], dayfirst=True)
ferien.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Zeitstempel  437 non-null    datetime64[ns]
 1   Ferientyp    437 non-null    object
 2   Ferien_bool  437 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 10.4+ KB

### Import Google Trends

In [5]:
# Import "Google Trends Mocafe.csv"
google_trends = pd.read_csv('google_trends_summe.csv', parse_dates=['Woche'], usecols=['Woche', 'summe'])
google_trends.head()

       Woche  summe
0 2018-01-07      0
1 2018-01-14      0
2 2018-01-21     72
3 2018-01-28      0
4 2018-02-04     36

In [6]:
# Import "Covid_restrictions.csv"
covid_restrictions = pd.read_csv('Covid_restrictions.csv', parse_dates=['Zeitstempel'], dayfirst=True)
covid_restrictions.head()

  Zeitstempel  Covid restrictions  Flu season
0  2018-01-01                   0           1
1  2018-01-02                   0           1
2  2018-01-03                   0           1
3  2018-01-04                   0           1
4  2018-01-05                   0           1

## Merge Data

### Merge Feiertage

In [7]:
# Merge data and feiertage
data_feiertag = pd.merge(data, feiertage, on='Zeitstempel', how='left')
# Recode NaN from Feiertag_bool to False and 1 to True
data_feiertag['Feiertag_bool'] = data_feiertag['Feiertag_bool'].fillna(0).astype(bool)
data_feiertag

,Artikel,ArtikelNr,Menge,Temperatur Schnitt Tag,Niederschlag Summe Tag,Globalstrahlung Schnitt Tag,Zeitstempel,day_of_week,day_of_year,month,year,Menge_log,Feiertag,Feiertag_bool
0,Berliner m Confi Himbeer of,521,5.0,3.800000,4.8,37.791667,2018-01-02,1,2,1,2018,1.791759,NaN,False
1,Berliner m Confi Himbeer of,521,4.0,7.200000,0.0,0.000000,2018-01-03,2,3,1,2018,1.609438,NaN,False
2,Berliner m Confi Himbeer of,521,3.0,9.216667,19.2,24.230769,2018-01-04,3,4,1,2018,1.386294,NaN,False
3,Berliner m Confi Himbeer of,521,7.0,10.600000,0.0,68.000000,2018-01-05,4,5,1,2018,2.079442,NaN,False
4,Berliner m Confi Himbeer of,521,9.0,3.411765,0.0,49.352941,2018-01-08,0,8,1,2018,2.302585,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22261,caffè crema,1178,27.0,10.091667,5.2,62.958333,2022-02-18,4,49,2,2022,3.332205,NaN,False
22262,caffè crema,1178,57.0,3.600000,7.6,59.125000,2022-02-19,5,50,2,2022,4.060443,NaN,False
22263,caffè crema,1178,75.0,6.908333,0.0,91.125000,2022-02-20,6,51,2,2022,4.330733,NaN,False
22264,caffè crema,1178,45.0,4.829167,13.0,48.666667,2022-02-21,0,52,2,2022,3.828641,NaN,False
22265,caffè crema,1178,39.0,5.187500,1.4,78.458333,2022-02-22,1,53,2,2022,3.688879,NaN,False

### Merge Ferien

In [8]:
# Merge data_feiertag and ferien
data_feiertag_ferien = pd.merge(data_feiertag, ferien, on='Zeitstempel', how='left')
# Recode NaN from Ferien_bool to False and 1 to True
data_feiertag_ferien['Ferien_bool'] = data_feiertag_ferien['Ferien_bool'].fillna(0).astype(bool)
data_feiertag_ferien

,Artikel,ArtikelNr,Menge,Temperatur Schnitt Tag,Niederschlag Summe Tag,Globalstrahlung Schnitt Tag,Zeitstempel,day_of_week,day_of_year,month,year,Menge_log,Feiertag,Feiertag_bool,Ferientyp,Ferien_bool
0,Berliner m Confi Himbeer of,521,5.0,3.800000,4.8,37.791667,2018-01-02,1,2,1,2018,1.791759,NaN,False,Wiehnachtsferien,True
1,Berliner m Confi Himbeer of,521,4.0,7.200000,0.0,0.000000,2018-01-03,2,3,1,2018,1.609438,NaN,False,Wiehnachtsferien,True
2,Berliner m Confi Himbeer of,521,3.0,9.216667,19.2,24.230769,2018-01-04,3,4,1,2018,1.386294,NaN,False,Wiehnachtsferien,True
3,Berliner m Confi Himbeer of,521,7.0,10.600000,0.0,68.000000,2018-01-05,4,5,1,2018,2.079442,NaN,False,Wiehnachtsferien,True
4,Berliner m Confi Himbeer of,521,9.0,3.411765,0.0,49.352941,2018-01-08,0,8,1,2018,2.302585,NaN,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22261,caffè crema,1178,27.0,10.091667,5.2,62.958333,2022-02-18,4,49,2,2022,3.332205,NaN,False,NaN,False
22262,caffè crema,1178,57.0,3.600000,7.6,59.125000,2022-02-19,5,50,2,2022,4.060443,NaN,False,NaN,False
22263,caffè crema,1178,75.0,6.908333,0.0,91.125000,2022-02-20,6,51,2,2022,4.330733,NaN,False,NaN,False
22264,caffè crema,1178,45.0,4.829167,13.0,48.666667,2022-02-21,0,52,2,2022,3.828641,NaN,False,NaN,False
22265,caffè crema,1178,39.0,5.187500,1.4,78.458333,2022-02-22,1,53,2,2022,3.688879,NaN,False,NaN,False

### Merge Google Trends

In [9]:
# Merge data_feiertag_ferien and google_trends, as weekly data isn't available in the future, we use always the previous week

# add previoius week to google_trends
google_trends['previous_week'] = google_trends['Woche'] - pd.Timedelta(days=7)

# Get week of year from Woche
google_trends['week_of_year'] = google_trends['previous_week'].dt.week
# Get year from Woche
google_trends['year'] = google_trends['previous_week'].dt.year
# Drop Woche and previous_week
google_trends_clean = google_trends.drop(['Woche', 'previous_week'], axis=1)
# Rename "Mocafe: (Schweiz)" to GTrends_Mocafe_PrevWeek
google_trends_clean = google_trends_clean.rename(columns={'summe': 'GTrends_Mocafe_PrevWeek'})

C:\Users\stoec\AppData\Local\Temp\ipykernel_27772\2430955479.py:7: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  google_trends['week_of_year'] = google_trends['previous_week'].dt.week

In [10]:
# Add week_of_year to data_feiertag_ferien
data_feiertag_ferien['week_of_year'] = data_feiertag_ferien['Zeitstempel'].dt.week

# merge by week of year and year
data_feiertag_ferien_google = pd.merge(data_feiertag_ferien, google_trends_clean, on=['week_of_year', 'year'], how='left')

# Replace NaN with 0 in GTrends_Mocafe_PrevWeek
data_feiertag_ferien_google['GTrends_Mocafe_PrevWeek'] = data_feiertag_ferien_google['GTrends_Mocafe_PrevWeek'].fillna(0)

C:\Users\stoec\AppData\Local\Temp\ipykernel_27772\2227713963.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  data_feiertag_ferien['week_of_year'] = data_feiertag_ferien['Zeitstempel'].dt.week

In [11]:
data_feiertag_ferien_google

,Artikel,ArtikelNr,Menge,Temperatur Schnitt Tag,Niederschlag Summe Tag,Globalstrahlung Schnitt Tag,Zeitstempel,day_of_week,day_of_year,month,year,Menge_log,Feiertag,Feiertag_bool,Ferientyp,Ferien_bool,week_of_year,GTrends_Mocafe_PrevWeek
0,Berliner m Confi Himbeer of,521,5.0,3.800000,4.8,37.791667,2018-01-02,1,2,1,2018,1.791759,NaN,False,Wiehnachtsferien,True,1,0.0
1,Berliner m Confi Himbeer of,521,4.0,7.200000,0.0,0.000000,2018-01-03,2,3,1,2018,1.609438,NaN,False,Wiehnachtsferien,True,1,0.0
2,Berliner m Confi Himbeer of,521,3.0,9.216667,19.2,24.230769,2018-01-04,3,4,1,2018,1.386294,NaN,False,Wiehnachtsferien,True,1,0.0
3,Berliner m Confi Himbeer of,521,7.0,10.600000,0.0,68.000000,2018-01-05,4,5,1,2018,2.079442,NaN,False,Wiehnachtsferien,True,1,0.0
4,Berliner m Confi Himbeer of,521,9.0,3.411765,0.0,49.352941,2018-01-08,0,8,1,2018,2.302585,NaN,False,NaN,False,2,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22261,caffè crema,1178,27.0,10.091667,5.2,62.958333,2022-02-18,4,49,2,2022,3.332205,NaN,False,NaN,False,7,72.0
22262,caffè crema,1178,57.0,3.600000,7.6,59.125000,2022-02-19,5,50,2,2022,4.060443,NaN,False,NaN,False,7,72.0
22263,caffè crema,1178,75.0,6.908333,0.0,91.125000,2022-02-20,6,51,2,2022,4.330733,NaN,False,NaN,False,7,72.0
22264,caffè crema,1178,45.0,4.829167,13.0,48.666667,2022-02-21,0,52,2,2022,3.828641,NaN,False,NaN,False,8,0.0
22265,caffè crema,1178,39.0,5.187500,1.4,78.458333,2022-02-22,1,53,2,2022,3.688879,NaN,False,NaN,False,8,0.0

In [12]:

# Merge data_feiertag and covid_data
data_feiertag_ferien_google_covid = pd.merge(data_feiertag_ferien_google, covid_restrictions, on='Zeitstempel', how='left')

In [13]:
data_feiertag_ferien_google_covid

,Artikel,ArtikelNr,Menge,Temperatur Schnitt Tag,Niederschlag Summe Tag,Globalstrahlung Schnitt Tag,Zeitstempel,day_of_week,day_of_year,month,year,Menge_log,Feiertag,Feiertag_bool,Ferientyp,Ferien_bool,week_of_year,GTrends_Mocafe_PrevWeek,Covid restrictions,Flu season
0,Berliner m Confi Himbeer of,521,5.0,3.800000,4.8,37.791667,2018-01-02,1,2,1,2018,1.791759,NaN,False,Wiehnachtsferien,True,1,0.0,0,1
1,Berliner m Confi Himbeer of,521,4.0,7.200000,0.0,0.000000,2018-01-03,2,3,1,2018,1.609438,NaN,False,Wiehnachtsferien,True,1,0.0,0,1
2,Berliner m Confi Himbeer of,521,3.0,9.216667,19.2,24.230769,2018-01-04,3,4,1,2018,1.386294,NaN,False,Wiehnachtsferien,True,1,0.0,0,1
3,Berliner m Confi Himbeer of,521,7.0,10.600000,0.0,68.000000,2018-01-05,4,5,1,2018,2.079442,NaN,False,Wiehnachtsferien,True,1,0.0,0,1
4,Berliner m Confi Himbeer of,521,9.0,3.411765,0.0,49.352941,2018-01-08,0,8,1,2018,2.302585,NaN,False,NaN,False,2,72.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22261,caffè crema,1178,27.0,10.091667,5.2,62.958333,2022-02-18,4,49,2,2022,3.332205,NaN,False,NaN,False,7,72.0,0,1
22262,caffè crema,1178,57.0,3.600000,7.6,59.125000,2022-02-19,5,50,2,2022,4.060443,NaN,False,NaN,False,7,72.0,0,1
22263,caffè crema,1178,75.0,6.908333,0.0,91.125000,2022-02-20,6,51,2,2022,4.330733,NaN,False,NaN,False,7,72.0,0,1
22264,caffè crema,1178,45.0,4.829167,13.0,48.666667,2022-02-21,0,52,2,2022,3.828641,NaN,False,NaN,False,8,0.0,0,1
22265,caffè crema,1178,39.0,5.187500,1.4,78.458333,2022-02-22,1,53,2,2022,3.688879,NaN,False,NaN,False,8,0.0,0,1

## Save new datafile

In [14]:
# Drop Feiertag column und Ferientyp
data_feiertag_ferien_google_covid = data_feiertag_ferien_google_covid.drop(['Feiertag', 'Ferientyp'], axis=1)

# Save new dataset to csv
data_feiertag_ferien_google_covid.to_csv('data_enriched.csv', index=False)

In [15]:
data_feiertag_ferien_google.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22266 entries, 0 to 22265
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Artikel                      22266 non-null  object
 1   ArtikelNr                    22266 non-null  int64
 2   Menge                        22266 non-null  float64
 3   Temperatur Schnitt Tag       22266 non-null  float64
 4   Niederschlag Summe Tag       22266 non-null  float64
 5   Globalstrahlung Schnitt Tag  22266 non-null  float64
 6   Zeitstempel                  22266 non-null  datetime64[ns]
 7   day_of_week                  22266 non-null  int64
 8   day_of_year                  22266 non-null  int64
 9   month                        22266 non-null  int64
 10  year                         22266 non-null  int64
 11  Menge_log                    22266 non-null  float64
 12  Feiertag                     194 non-null    object
 13  Feiertag_bool                22266 non-null  bool
 14  Ferientyp                    5247 non-null   object
 15  Ferien_bool                  22266 non-null  bool
 16  week_of_year                 22266 non-null  int64
 17  GTrends_Mocafe_PrevWeek      22266 non-null  float64
dtypes: bool(2), datetime64[ns](1), float64(6), int64(6), object(3)
memory usage: 2.9+ MB